// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/round/domain/usecases/correct_bids_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:la_pocha/features/game_setup/domain/entities/round.dart' as _i2;
import 'package:la_pocha/features/game_setup/domain/repositories/round_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRound_0 extends _i1.SmartFake implements _i2.Round {
  _FakeRound_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RoundRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoundRepository extends _i1.Mock implements _i3.RoundRepository {
  @override
  _i4.Future<_i2.Round> insertRound(_i2.Round? round) =>
      (super.noSuchMethod(
            Invocation.method(#insertRound, [round]),
            returnValue: _i4.Future<_i2.Round>.value(
              _FakeRound_0(this, Invocation.method(#insertRound, [round])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Round>.value(
              _FakeRound_0(this, Invocation.method(#insertRound, [round])),
            ),
          )
          as _i4.Future<_i2.Round>);

  @override
  _i4.Future<_i2.Round?> getRoundByGameAndNumber(
    String? gameId,
    int? roundNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRoundByGameAndNumber, [gameId, roundNumber]),
            returnValue: _i4.Future<_i2.Round?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Round?>.value(),
          )
          as _i4.Future<_i2.Round?>);

  @override
  _i4.Future<List<_i2.Round>> getRoundsByGameId(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoundsByGameId, [gameId]),
            returnValue: _i4.Future<List<_i2.Round>>.value(<_i2.Round>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Round>>.value(
              <_i2.Round>[],
            ),
          )
          as _i4.Future<List<_i2.Round>>);

  @override
  _i4.Future<_i2.Round> updateRound(_i2.Round? round) =>
      (super.noSuchMethod(
            Invocation.method(#updateRound, [round]),
            returnValue: _i4.Future<_i2.Round>.value(
              _FakeRound_0(this, Invocation.method(#updateRound, [round])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Round>.value(
              _FakeRound_0(this, Invocation.method(#updateRound, [round])),
            ),
          )
          as _i4.Future<_i2.Round>);
}
