// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/round/domain/usecases/get_game_scorecard_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:la_pocha/features/game_setup/domain/entities/game.dart' as _i2;
import 'package:la_pocha/features/game_setup/domain/entities/player_embed.dart'
    as _i7;
import 'package:la_pocha/features/game_setup/domain/entities/round.dart' as _i4;
import 'package:la_pocha/features/game_setup/domain/entities/start_game_result.dart'
    as _i3;
import 'package:la_pocha/features/game_setup/domain/repositories/game_repository.dart'
    as _i5;
import 'package:la_pocha/features/game_setup/domain/repositories/round_repository.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGame_0 extends _i1.SmartFake implements _i2.Game {
  _FakeGame_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStartGameResult_1 extends _i1.SmartFake
    implements _i3.StartGameResult {
  _FakeStartGameResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRound_2 extends _i1.SmartFake implements _i4.Round {
  _FakeRound_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i5.GameRepository {
  @override
  _i6.Future<_i2.Game> saveDraft(_i2.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [game]),
            returnValue: _i6.Future<_i2.Game>.value(
              _FakeGame_0(this, Invocation.method(#saveDraft, [game])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Game>.value(
              _FakeGame_0(this, Invocation.method(#saveDraft, [game])),
            ),
          )
          as _i6.Future<_i2.Game>);

  @override
  _i6.Future<_i2.Game?> getGameById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGameById, [id]),
            returnValue: _i6.Future<_i2.Game?>.value(),
            returnValueForMissingStub: _i6.Future<_i2.Game?>.value(),
          )
          as _i6.Future<_i2.Game?>);

  @override
  _i6.Future<_i2.Game?> getInProgressGame() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressGame, []),
            returnValue: _i6.Future<_i2.Game?>.value(),
            returnValueForMissingStub: _i6.Future<_i2.Game?>.value(),
          )
          as _i6.Future<_i2.Game?>);

  @override
  _i6.Future<_i2.Game> updateGamePlayers(
    String? gameId,
    List<_i7.PlayerEmbed>? players,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGamePlayers, [gameId, players]),
            returnValue: _i6.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#updateGamePlayers, [gameId, players]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#updateGamePlayers, [gameId, players]),
              ),
            ),
          )
          as _i6.Future<_i2.Game>);

  @override
  _i6.Future<_i3.StartGameResult> startGame({
    required String? gameId,
    required List<_i7.PlayerEmbed>? players,
    required String? firstDealerPlayerId,
    required _i4.Round? firstRound,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startGame, [], {
              #gameId: gameId,
              #players: players,
              #firstDealerPlayerId: firstDealerPlayerId,
              #firstRound: firstRound,
            }),
            returnValue: _i6.Future<_i3.StartGameResult>.value(
              _FakeStartGameResult_1(
                this,
                Invocation.method(#startGame, [], {
                  #gameId: gameId,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                  #firstRound: firstRound,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.StartGameResult>.value(
              _FakeStartGameResult_1(
                this,
                Invocation.method(#startGame, [], {
                  #gameId: gameId,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                  #firstRound: firstRound,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.StartGameResult>);

  @override
  _i6.Future<void> revertGameToSetup(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#revertGameToSetup, [gameId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.Round> closeRoundAndUpdateScores({
    required _i4.Round? closedRound,
    required List<_i7.PlayerEmbed>? updatedPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#closeRoundAndUpdateScores, [], {
              #closedRound: closedRound,
              #updatedPlayers: updatedPlayers,
            }),
            returnValue: _i6.Future<_i4.Round>.value(
              _FakeRound_2(
                this,
                Invocation.method(#closeRoundAndUpdateScores, [], {
                  #closedRound: closedRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Round>.value(
              _FakeRound_2(
                this,
                Invocation.method(#closeRoundAndUpdateScores, [], {
                  #closedRound: closedRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Round>);

  @override
  _i6.Future<_i4.Round> repeatRoundAndRevertScores({
    required _i4.Round? resetRound,
    required List<_i7.PlayerEmbed>? updatedPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#repeatRoundAndRevertScores, [], {
              #resetRound: resetRound,
              #updatedPlayers: updatedPlayers,
            }),
            returnValue: _i6.Future<_i4.Round>.value(
              _FakeRound_2(
                this,
                Invocation.method(#repeatRoundAndRevertScores, [], {
                  #resetRound: resetRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Round>.value(
              _FakeRound_2(
                this,
                Invocation.method(#repeatRoundAndRevertScores, [], {
                  #resetRound: resetRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Round>);

  @override
  _i6.Future<_i4.Round> advanceToNextRound({
    required _i4.Round? nextRound,
    required int? nextRoundNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#advanceToNextRound, [], {
              #nextRound: nextRound,
              #nextRoundNumber: nextRoundNumber,
            }),
            returnValue: _i6.Future<_i4.Round>.value(
              _FakeRound_2(
                this,
                Invocation.method(#advanceToNextRound, [], {
                  #nextRound: nextRound,
                  #nextRoundNumber: nextRoundNumber,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Round>.value(
              _FakeRound_2(
                this,
                Invocation.method(#advanceToNextRound, [], {
                  #nextRound: nextRound,
                  #nextRoundNumber: nextRoundNumber,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Round>);

  @override
  _i6.Future<_i2.Game> finishGame({
    required String? gameId,
    required DateTime? finishedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finishGame, [], {
              #gameId: gameId,
              #finishedAt: finishedAt,
            }),
            returnValue: _i6.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#finishGame, [], {
                  #gameId: gameId,
                  #finishedAt: finishedAt,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#finishGame, [], {
                  #gameId: gameId,
                  #finishedAt: finishedAt,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.Game>);

  @override
  _i6.Future<void> deleteGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGame, [gameId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [RoundRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoundRepository extends _i1.Mock implements _i8.RoundRepository {
  @override
  _i6.Future<_i4.Round> insertRound(_i4.Round? round) =>
      (super.noSuchMethod(
            Invocation.method(#insertRound, [round]),
            returnValue: _i6.Future<_i4.Round>.value(
              _FakeRound_2(this, Invocation.method(#insertRound, [round])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Round>.value(
              _FakeRound_2(this, Invocation.method(#insertRound, [round])),
            ),
          )
          as _i6.Future<_i4.Round>);

  @override
  _i6.Future<_i4.Round?> getRoundByGameAndNumber(
    String? gameId,
    int? roundNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRoundByGameAndNumber, [gameId, roundNumber]),
            returnValue: _i6.Future<_i4.Round?>.value(),
            returnValueForMissingStub: _i6.Future<_i4.Round?>.value(),
          )
          as _i6.Future<_i4.Round?>);

  @override
  _i6.Future<List<_i4.Round>> getRoundsByGameId(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoundsByGameId, [gameId]),
            returnValue: _i6.Future<List<_i4.Round>>.value(<_i4.Round>[]),
            returnValueForMissingStub: _i6.Future<List<_i4.Round>>.value(
              <_i4.Round>[],
            ),
          )
          as _i6.Future<List<_i4.Round>>);

  @override
  _i6.Future<_i4.Round> updateRound(_i4.Round? round) =>
      (super.noSuchMethod(
            Invocation.method(#updateRound, [round]),
            returnValue: _i6.Future<_i4.Round>.value(
              _FakeRound_2(this, Invocation.method(#updateRound, [round])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Round>.value(
              _FakeRound_2(this, Invocation.method(#updateRound, [round])),
            ),
          )
          as _i6.Future<_i4.Round>);
}
