// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/sync/domain/usecases/upload_finished_game_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:connectivity_plus/connectivity_plus.dart' as _i11;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i12;
import 'package:la_pocha/features/auth/domain/entities/user_profile.dart'
    as _i2;
import 'package:la_pocha/features/auth/domain/repositories/auth_repository.dart'
    as _i6;
import 'package:la_pocha/features/game_setup/data/datasources/game_local_datasource.dart'
    as _i9;
import 'package:la_pocha/features/game_setup/domain/entities/game.dart' as _i3;
import 'package:la_pocha/features/game_setup/domain/entities/player_embed.dart'
    as _i10;
import 'package:la_pocha/features/game_setup/domain/entities/round.dart' as _i5;
import 'package:la_pocha/features/game_setup/domain/entities/start_game_result.dart'
    as _i4;
import 'package:la_pocha/features/sync/domain/repositories/game_sync_repository.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGame_1 extends _i1.SmartFake implements _i3.Game {
  _FakeGame_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStartGameResult_2 extends _i1.SmartFake
    implements _i4.StartGameResult {
  _FakeStartGameResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRound_3 extends _i1.SmartFake implements _i5.Round {
  _FakeRound_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i2.UserProfile?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i7.Stream<_i2.UserProfile?>.empty(),
          )
          as _i7.Stream<_i2.UserProfile?>);

  @override
  _i7.Future<_i2.UserProfile> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i7.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.UserProfile>);

  @override
  _i7.Future<_i2.UserProfile> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i7.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.UserProfile>);

  @override
  _i7.Future<_i2.UserProfile?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i7.Future<_i2.UserProfile?>.value(),
          )
          as _i7.Future<_i2.UserProfile?>);

  @override
  _i7.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> sendPasswordReset({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordReset, [], {#email: email}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.UserProfile?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i7.Future<_i2.UserProfile?>.value(),
          )
          as _i7.Future<_i2.UserProfile?>);

  @override
  _i7.Future<_i2.UserProfile> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i7.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#updateDisplayName, [displayName]),
              ),
            ),
          )
          as _i7.Future<_i2.UserProfile>);

  @override
  _i7.Future<void> deleteAccount({String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [], {#password: password}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [GameSyncRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameSyncRepository extends _i1.Mock
    implements _i8.GameSyncRepository {
  MockGameSyncRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.GameUploadResult> uploadFinishedGame({
    required String? gameId,
    required String? hostId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFinishedGame, [], {
              #gameId: gameId,
              #hostId: hostId,
            }),
            returnValue: _i7.Future<_i8.GameUploadResult>.value(
              _i8.GameUploadResult.synced,
            ),
          )
          as _i7.Future<_i8.GameUploadResult>);

  @override
  _i7.Future<List<_i3.Game>> getPendingGames() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingGames, []),
            returnValue: _i7.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i7.Future<List<_i3.Game>>);
}

/// A class which mocks [GameLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameLocalDatasource extends _i1.Mock
    implements _i9.GameLocalDatasource {
  MockGameLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.Game> insertGame(_i3.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#insertGame, [game]),
            returnValue: _i7.Future<_i3.Game>.value(
              _FakeGame_1(this, Invocation.method(#insertGame, [game])),
            ),
          )
          as _i7.Future<_i3.Game>);

  @override
  _i7.Future<_i3.Game?> getGameById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGameById, [id]),
            returnValue: _i7.Future<_i3.Game?>.value(),
          )
          as _i7.Future<_i3.Game?>);

  @override
  _i7.Future<_i3.Game?> getInProgressGame() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressGame, []),
            returnValue: _i7.Future<_i3.Game?>.value(),
          )
          as _i7.Future<_i3.Game?>);

  @override
  _i7.Future<_i3.Game> updateGamePlayers(
    String? gameId,
    List<_i10.PlayerEmbed>? players,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGamePlayers, [gameId, players]),
            returnValue: _i7.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#updateGamePlayers, [gameId, players]),
              ),
            ),
          )
          as _i7.Future<_i3.Game>);

  @override
  _i7.Future<_i4.StartGameResult> startGame({
    required String? gameId,
    required List<_i10.PlayerEmbed>? players,
    required String? firstDealerPlayerId,
    required _i5.Round? firstRound,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startGame, [], {
              #gameId: gameId,
              #players: players,
              #firstDealerPlayerId: firstDealerPlayerId,
              #firstRound: firstRound,
            }),
            returnValue: _i7.Future<_i4.StartGameResult>.value(
              _FakeStartGameResult_2(
                this,
                Invocation.method(#startGame, [], {
                  #gameId: gameId,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                  #firstRound: firstRound,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.StartGameResult>);

  @override
  _i7.Future<void> revertGameToSetup(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#revertGameToSetup, [gameId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.Round> closeRoundAndUpdateScores({
    required _i5.Round? closedRound,
    required List<_i10.PlayerEmbed>? updatedPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#closeRoundAndUpdateScores, [], {
              #closedRound: closedRound,
              #updatedPlayers: updatedPlayers,
            }),
            returnValue: _i7.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#closeRoundAndUpdateScores, [], {
                  #closedRound: closedRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.Round>);

  @override
  _i7.Future<_i5.Round> repeatRoundAndRevertScores({
    required _i5.Round? resetRound,
    required List<_i10.PlayerEmbed>? updatedPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#repeatRoundAndRevertScores, [], {
              #resetRound: resetRound,
              #updatedPlayers: updatedPlayers,
            }),
            returnValue: _i7.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#repeatRoundAndRevertScores, [], {
                  #resetRound: resetRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.Round>);

  @override
  _i7.Future<_i5.Round> advanceToNextRound({
    required _i5.Round? nextRound,
    required int? nextRoundNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#advanceToNextRound, [], {
              #nextRound: nextRound,
              #nextRoundNumber: nextRoundNumber,
            }),
            returnValue: _i7.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#advanceToNextRound, [], {
                  #nextRound: nextRound,
                  #nextRoundNumber: nextRoundNumber,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.Round>);

  @override
  _i7.Future<_i3.Game> finishGame({
    required String? gameId,
    required DateTime? finishedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finishGame, [], {
              #gameId: gameId,
              #finishedAt: finishedAt,
            }),
            returnValue: _i7.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#finishGame, [], {
                  #gameId: gameId,
                  #finishedAt: finishedAt,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.Game>);

  @override
  _i7.Future<void> deleteGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGame, [gameId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.Game> updateSyncMetadata({
    required String? gameId,
    String? cloudGameId,
    required String? syncStatus,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSyncMetadata, [], {
              #gameId: gameId,
              #cloudGameId: cloudGameId,
              #syncStatus: syncStatus,
            }),
            returnValue: _i7.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#updateSyncMetadata, [], {
                  #gameId: gameId,
                  #cloudGameId: cloudGameId,
                  #syncStatus: syncStatus,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.Game>);

  @override
  _i7.Future<List<_i3.Game>> getGamesBySyncStatus(String? syncStatus) =>
      (super.noSuchMethod(
            Invocation.method(#getGamesBySyncStatus, [syncStatus]),
            returnValue: _i7.Future<List<_i3.Game>>.value(<_i3.Game>[]),
          )
          as _i7.Future<List<_i3.Game>>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i11.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<List<_i12.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i7.Stream<List<_i12.ConnectivityResult>>.empty(),
          )
          as _i7.Stream<List<_i12.ConnectivityResult>>);

  @override
  _i7.Future<List<_i12.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i7.Future<List<_i12.ConnectivityResult>>.value(
              <_i12.ConnectivityResult>[],
            ),
          )
          as _i7.Future<List<_i12.ConnectivityResult>>);
}
