// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/game_setup/presentation/bloc/add_players_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:la_pocha/features/auth/domain/entities/user_profile.dart'
    as _i8;
import 'package:la_pocha/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i7;
import 'package:la_pocha/features/favorites/domain/entities/favorite_player.dart'
    as _i3;
import 'package:la_pocha/features/favorites/domain/usecases/add_favorite_usecase.dart'
    as _i13;
import 'package:la_pocha/features/favorites/domain/usecases/get_favorites_usecase.dart'
    as _i6;
import 'package:la_pocha/features/favorites/domain/usecases/remove_favorite_usecase.dart'
    as _i14;
import 'package:la_pocha/features/game_setup/domain/entities/game.dart' as _i2;
import 'package:la_pocha/features/game_setup/domain/usecases/add_player_from_favorite_usecase.dart'
    as _i10;
import 'package:la_pocha/features/game_setup/domain/usecases/add_player_usecase.dart'
    as _i9;
import 'package:la_pocha/features/game_setup/domain/usecases/get_game_by_id_usecase.dart'
    as _i4;
import 'package:la_pocha/features/game_setup/domain/usecases/remove_player_usecase.dart'
    as _i11;
import 'package:la_pocha/features/game_setup/domain/usecases/update_player_name_usecase.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGame_0 extends _i1.SmartFake implements _i2.Game {
  _FakeGame_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFavoritePlayer_1 extends _i1.SmartFake
    implements _i3.FavoritePlayer {
  _FakeFavoritePlayer_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetGameByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGameByIdUseCase extends _i1.Mock
    implements _i4.GetGameByIdUseCase {
  @override
  _i5.Future<_i2.Game?> call(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [gameId]),
            returnValue: _i5.Future<_i2.Game?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.Game?>.value(),
          )
          as _i5.Future<_i2.Game?>);
}

/// A class which mocks [GetFavoritesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavoritesUseCase extends _i1.Mock
    implements _i6.GetFavoritesUseCase {
  @override
  _i5.Future<List<_i3.FavoritePlayer>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<List<_i3.FavoritePlayer>>.value(
              <_i3.FavoritePlayer>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i3.FavoritePlayer>>.value(
                  <_i3.FavoritePlayer>[],
                ),
          )
          as _i5.Future<List<_i3.FavoritePlayer>>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i7.GetCurrentUserUseCase {
  @override
  _i5.Future<_i8.UserProfile?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<_i8.UserProfile?>.value(),
            returnValueForMissingStub: _i5.Future<_i8.UserProfile?>.value(),
          )
          as _i5.Future<_i8.UserProfile?>);
}

/// A class which mocks [AddPlayerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddPlayerUseCase extends _i1.Mock implements _i9.AddPlayerUseCase {
  @override
  _i5.Future<_i2.Game> call({required String? gameId, required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#gameId: gameId, #name: name}),
            returnValue: _i5.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#call, [], {#gameId: gameId, #name: name}),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#call, [], {#gameId: gameId, #name: name}),
              ),
            ),
          )
          as _i5.Future<_i2.Game>);
}

/// A class which mocks [AddPlayerFromFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddPlayerFromFavoriteUseCase extends _i1.Mock
    implements _i10.AddPlayerFromFavoriteUseCase {
  @override
  _i5.Future<_i2.Game> call({
    required String? gameId,
    required String? favoriteId,
    _i3.FavoritePlayer? favorite,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #gameId: gameId,
              #favoriteId: favoriteId,
              #favorite: favorite,
            }),
            returnValue: _i5.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #favoriteId: favoriteId,
                  #favorite: favorite,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #favoriteId: favoriteId,
                  #favorite: favorite,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Game>);
}

/// A class which mocks [RemovePlayerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemovePlayerUseCase extends _i1.Mock
    implements _i11.RemovePlayerUseCase {
  @override
  _i5.Future<_i2.Game?> call({
    required String? gameId,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #gameId: gameId,
              #playerId: playerId,
            }),
            returnValue: _i5.Future<_i2.Game?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.Game?>.value(),
          )
          as _i5.Future<_i2.Game?>);
}

/// A class which mocks [UpdatePlayerNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePlayerNameUseCase extends _i1.Mock
    implements _i12.UpdatePlayerNameUseCase {
  @override
  _i5.Future<_i2.Game> call({
    required String? gameId,
    required String? playerId,
    required String? newName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #gameId: gameId,
              #playerId: playerId,
              #newName: newName,
            }),
            returnValue: _i5.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #playerId: playerId,
                  #newName: newName,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Game>.value(
              _FakeGame_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #playerId: playerId,
                  #newName: newName,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Game>);
}

/// A class which mocks [AddFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddFavoriteUseCase extends _i1.Mock
    implements _i13.AddFavoriteUseCase {
  @override
  _i5.Future<_i3.FavoritePlayer> call({
    required String? displayName,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #displayName: displayName,
              #userId: userId,
            }),
            returnValue: _i5.Future<_i3.FavoritePlayer>.value(
              _FakeFavoritePlayer_1(
                this,
                Invocation.method(#call, [], {
                  #displayName: displayName,
                  #userId: userId,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.FavoritePlayer>.value(
              _FakeFavoritePlayer_1(
                this,
                Invocation.method(#call, [], {
                  #displayName: displayName,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.FavoritePlayer>);
}

/// A class which mocks [RemoveFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveFavoriteUseCase extends _i1.Mock
    implements _i14.RemoveFavoriteUseCase {
  @override
  _i5.Future<void> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
