// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/game_setup/presentation/bloc/game_setup_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:la_pocha/features/game_setup/domain/entities/game.dart' as _i5;
import 'package:la_pocha/features/game_setup/domain/entities/player_embed.dart'
    as _i7;
import 'package:la_pocha/features/game_setup/domain/entities/start_game_result.dart'
    as _i2;
import 'package:la_pocha/features/game_setup/domain/usecases/get_game_by_id_usecase.dart'
    as _i3;
import 'package:la_pocha/features/game_setup/domain/usecases/randomize_first_dealer_usecase.dart'
    as _i10;
import 'package:la_pocha/features/game_setup/domain/usecases/reorder_players_usecase.dart'
    as _i6;
import 'package:la_pocha/features/game_setup/domain/usecases/set_first_dealer_usecase.dart'
    as _i8;
import 'package:la_pocha/features/game_setup/domain/usecases/start_game_usecase.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStartGameResult_0 extends _i1.SmartFake
    implements _i2.StartGameResult {
  _FakeStartGameResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetGameByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGameByIdUseCase extends _i1.Mock
    implements _i3.GetGameByIdUseCase {
  @override
  _i4.Future<_i5.Game?> call(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [gameId]),
            returnValue: _i4.Future<_i5.Game?>.value(),
            returnValueForMissingStub: _i4.Future<_i5.Game?>.value(),
          )
          as _i4.Future<_i5.Game?>);
}

/// A class which mocks [ReorderPlayersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReorderPlayersUseCase extends _i1.Mock
    implements _i6.ReorderPlayersUseCase {
  @override
  List<_i7.PlayerEmbed> call({
    required List<_i7.PlayerEmbed>? players,
    required int? oldIndex,
    required int? newIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #players: players,
              #oldIndex: oldIndex,
              #newIndex: newIndex,
            }),
            returnValue: <_i7.PlayerEmbed>[],
            returnValueForMissingStub: <_i7.PlayerEmbed>[],
          )
          as List<_i7.PlayerEmbed>);
}

/// A class which mocks [SetFirstDealerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetFirstDealerUseCase extends _i1.Mock
    implements _i8.SetFirstDealerUseCase {
  @override
  String call({
    required List<_i7.PlayerEmbed>? players,
    required String? playerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #players: players,
              #playerId: playerId,
            }),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#call, [], {
                #players: players,
                #playerId: playerId,
              }),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#call, [], {
                #players: players,
                #playerId: playerId,
              }),
            ),
          )
          as String);
}

/// A class which mocks [RandomizeFirstDealerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRandomizeFirstDealerUseCase extends _i1.Mock
    implements _i10.RandomizeFirstDealerUseCase {
  @override
  String call({required List<_i7.PlayerEmbed>? players}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#players: players}),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#call, [], {#players: players}),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#call, [], {#players: players}),
            ),
          )
          as String);
}

/// A class which mocks [StartGameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartGameUseCase extends _i1.Mock implements _i11.StartGameUseCase {
  @override
  _i4.Future<_i2.StartGameResult> call({
    required _i5.Game? game,
    required List<_i7.PlayerEmbed>? players,
    required String? firstDealerPlayerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #game: game,
              #players: players,
              #firstDealerPlayerId: firstDealerPlayerId,
            }),
            returnValue: _i4.Future<_i2.StartGameResult>.value(
              _FakeStartGameResult_0(
                this,
                Invocation.method(#call, [], {
                  #game: game,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.StartGameResult>.value(
              _FakeStartGameResult_0(
                this,
                Invocation.method(#call, [], {
                  #game: game,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.StartGameResult>);
}
