// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/auth/domain/usecases/delete_account_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:la_pocha/features/auth/domain/entities/user_profile.dart'
    as _i2;
import 'package:la_pocha/features/auth/domain/repositories/auth_repository.dart'
    as _i6;
import 'package:la_pocha/features/favorites/domain/entities/favorite_player.dart'
    as _i3;
import 'package:la_pocha/features/favorites/domain/repositories/favorite_repository.dart'
    as _i8;
import 'package:la_pocha/features/history/domain/entities/game_detail.dart'
    as _i5;
import 'package:la_pocha/features/history/domain/entities/game_history_item.dart'
    as _i10;
import 'package:la_pocha/features/history/domain/entities/game_history_load_result.dart'
    as _i4;
import 'package:la_pocha/features/history/domain/entities/game_history_source.dart'
    as _i11;
import 'package:la_pocha/features/history/domain/repositories/history_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFavoritePlayer_1 extends _i1.SmartFake
    implements _i3.FavoritePlayer {
  _FakeFavoritePlayer_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameHistoryLoadResult_2 extends _i1.SmartFake
    implements _i4.GameHistoryLoadResult {
  _FakeGameHistoryLoadResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameDetail_3 extends _i1.SmartFake implements _i5.GameDetail {
  _FakeGameDetail_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  @override
  _i7.Stream<_i2.UserProfile?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i7.Stream<_i2.UserProfile?>.empty(),
            returnValueForMissingStub: _i7.Stream<_i2.UserProfile?>.empty(),
          )
          as _i7.Stream<_i2.UserProfile?>);

  @override
  _i7.Future<_i2.UserProfile> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i7.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.UserProfile>);

  @override
  _i7.Future<_i2.UserProfile> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i7.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.UserProfile>);

  @override
  _i7.Future<_i2.UserProfile?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i7.Future<_i2.UserProfile?>.value(),
            returnValueForMissingStub: _i7.Future<_i2.UserProfile?>.value(),
          )
          as _i7.Future<_i2.UserProfile?>);

  @override
  _i7.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> sendPasswordReset({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordReset, [], {#email: email}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.UserProfile?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i7.Future<_i2.UserProfile?>.value(),
            returnValueForMissingStub: _i7.Future<_i2.UserProfile?>.value(),
          )
          as _i7.Future<_i2.UserProfile?>);

  @override
  _i7.Future<_i2.UserProfile> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i7.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#updateDisplayName, [displayName]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#updateDisplayName, [displayName]),
              ),
            ),
          )
          as _i7.Future<_i2.UserProfile>);

  @override
  _i7.Future<void> deleteAccount({String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [], {#password: password}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [FavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRepository extends _i1.Mock
    implements _i8.FavoriteRepository {
  @override
  _i7.Future<List<_i3.FavoritePlayer>> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue: _i7.Future<List<_i3.FavoritePlayer>>.value(
              <_i3.FavoritePlayer>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i3.FavoritePlayer>>.value(
                  <_i3.FavoritePlayer>[],
                ),
          )
          as _i7.Future<List<_i3.FavoritePlayer>>);

  @override
  _i7.Future<_i3.FavoritePlayer> addFavorite({
    required String? displayName,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [], {
              #displayName: displayName,
              #userId: userId,
            }),
            returnValue: _i7.Future<_i3.FavoritePlayer>.value(
              _FakeFavoritePlayer_1(
                this,
                Invocation.method(#addFavorite, [], {
                  #displayName: displayName,
                  #userId: userId,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.FavoritePlayer>.value(
              _FakeFavoritePlayer_1(
                this,
                Invocation.method(#addFavorite, [], {
                  #displayName: displayName,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.FavoritePlayer>);

  @override
  _i7.Future<void> removeFavorite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavorite, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i9.HistoryRepository {
  @override
  _i7.Future<_i4.GameHistoryLoadResult> getGameHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getGameHistory, []),
            returnValue: _i7.Future<_i4.GameHistoryLoadResult>.value(
              _FakeGameHistoryLoadResult_2(
                this,
                Invocation.method(#getGameHistory, []),
              ),
            ),
            returnValueForMissingStub:
                _i7.Future<_i4.GameHistoryLoadResult>.value(
                  _FakeGameHistoryLoadResult_2(
                    this,
                    Invocation.method(#getGameHistory, []),
                  ),
                ),
          )
          as _i7.Future<_i4.GameHistoryLoadResult>);

  @override
  _i7.Stream<_i4.GameHistoryLoadResult> watchGameHistory() =>
      (super.noSuchMethod(
            Invocation.method(#watchGameHistory, []),
            returnValue: _i7.Stream<_i4.GameHistoryLoadResult>.empty(),
            returnValueForMissingStub:
                _i7.Stream<_i4.GameHistoryLoadResult>.empty(),
          )
          as _i7.Stream<_i4.GameHistoryLoadResult>);

  @override
  _i7.Future<List<_i10.GameHistoryItem>> getRecentFinishedGames({
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentFinishedGames, [], {#limit: limit}),
            returnValue: _i7.Future<List<_i10.GameHistoryItem>>.value(
              <_i10.GameHistoryItem>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i10.GameHistoryItem>>.value(
                  <_i10.GameHistoryItem>[],
                ),
          )
          as _i7.Future<List<_i10.GameHistoryItem>>);

  @override
  _i7.Stream<List<_i10.GameHistoryItem>> watchRecentFinishedGames({
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchRecentFinishedGames, [], {#limit: limit}),
            returnValue: _i7.Stream<List<_i10.GameHistoryItem>>.empty(),
            returnValueForMissingStub:
                _i7.Stream<List<_i10.GameHistoryItem>>.empty(),
          )
          as _i7.Stream<List<_i10.GameHistoryItem>>);

  @override
  _i7.Future<_i5.GameDetail> getGameDetail({
    required String? gameId,
    required _i11.GameHistorySource? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGameDetail, [], {
              #gameId: gameId,
              #source: source,
            }),
            returnValue: _i7.Future<_i5.GameDetail>.value(
              _FakeGameDetail_3(
                this,
                Invocation.method(#getGameDetail, [], {
                  #gameId: gameId,
                  #source: source,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.GameDetail>.value(
              _FakeGameDetail_3(
                this,
                Invocation.method(#getGameDetail, [], {
                  #gameId: gameId,
                  #source: source,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.GameDetail>);

  @override
  _i7.Future<void> deleteLocalGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalGame, [gameId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> hideCloudGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#hideCloudGame, [gameId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearHiddenGames() =>
      (super.noSuchMethod(
            Invocation.method(#clearHiddenGames, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
