// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/auth/domain/usecases/logout_with_cleanup_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:la_pocha/core/services/local_user_service.dart' as _i12;
import 'package:la_pocha/features/auth/domain/entities/user_profile.dart'
    as _i2;
import 'package:la_pocha/features/auth/domain/repositories/auth_repository.dart'
    as _i7;
import 'package:la_pocha/features/favorites/domain/entities/favorite_player.dart'
    as _i6;
import 'package:la_pocha/features/favorites/domain/repositories/favorite_repository.dart'
    as _i11;
import 'package:la_pocha/features/game_setup/domain/entities/game.dart' as _i3;
import 'package:la_pocha/features/game_setup/domain/entities/player_embed.dart'
    as _i10;
import 'package:la_pocha/features/game_setup/domain/entities/round.dart' as _i5;
import 'package:la_pocha/features/game_setup/domain/entities/start_game_result.dart'
    as _i4;
import 'package:la_pocha/features/game_setup/domain/repositories/game_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGame_1 extends _i1.SmartFake implements _i3.Game {
  _FakeGame_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStartGameResult_2 extends _i1.SmartFake
    implements _i4.StartGameResult {
  _FakeStartGameResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRound_3 extends _i1.SmartFake implements _i5.Round {
  _FakeRound_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFavoritePlayer_4 extends _i1.SmartFake
    implements _i6.FavoritePlayer {
  _FakeFavoritePlayer_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  @override
  _i8.Stream<_i2.UserProfile?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i8.Stream<_i2.UserProfile?>.empty(),
            returnValueForMissingStub: _i8.Stream<_i2.UserProfile?>.empty(),
          )
          as _i8.Stream<_i2.UserProfile?>);

  @override
  _i8.Future<_i2.UserProfile> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i8.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.UserProfile>);

  @override
  _i8.Future<_i2.UserProfile> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i8.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.UserProfile>);

  @override
  _i8.Future<_i2.UserProfile?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i8.Future<_i2.UserProfile?>.value(),
            returnValueForMissingStub: _i8.Future<_i2.UserProfile?>.value(),
          )
          as _i8.Future<_i2.UserProfile?>);

  @override
  _i8.Future<_i2.UserProfile> linkGoogleAccountWithPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkGoogleAccountWithPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i8.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#linkGoogleAccountWithPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#linkGoogleAccountWithPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.UserProfile>);

  @override
  _i8.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> linkLocalId({
    required String? firebaseUid,
    required String? localId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkLocalId, [], {
              #firebaseUid: firebaseUid,
              #localId: localId,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> sendPasswordReset({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordReset, [], {#email: email}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.UserProfile?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i8.Future<_i2.UserProfile?>.value(),
            returnValueForMissingStub: _i8.Future<_i2.UserProfile?>.value(),
          )
          as _i8.Future<_i2.UserProfile?>);

  @override
  _i8.Future<_i2.UserProfile> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i8.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#updateDisplayName, [displayName]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#updateDisplayName, [displayName]),
              ),
            ),
          )
          as _i8.Future<_i2.UserProfile>);

  @override
  _i8.Future<void> deleteAccount({String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [], {#password: password}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i9.GameRepository {
  @override
  _i8.Future<_i3.Game> saveDraft(_i3.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [game]),
            returnValue: _i8.Future<_i3.Game>.value(
              _FakeGame_1(this, Invocation.method(#saveDraft, [game])),
            ),
            returnValueForMissingStub: _i8.Future<_i3.Game>.value(
              _FakeGame_1(this, Invocation.method(#saveDraft, [game])),
            ),
          )
          as _i8.Future<_i3.Game>);

  @override
  _i8.Future<_i3.Game?> getGameById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGameById, [id]),
            returnValue: _i8.Future<_i3.Game?>.value(),
            returnValueForMissingStub: _i8.Future<_i3.Game?>.value(),
          )
          as _i8.Future<_i3.Game?>);

  @override
  _i8.Future<_i3.Game?> getInProgressGame() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressGame, []),
            returnValue: _i8.Future<_i3.Game?>.value(),
            returnValueForMissingStub: _i8.Future<_i3.Game?>.value(),
          )
          as _i8.Future<_i3.Game?>);

  @override
  _i8.Future<_i3.Game> updateGamePlayers(
    String? gameId,
    List<_i10.PlayerEmbed>? players,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGamePlayers, [gameId, players]),
            returnValue: _i8.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#updateGamePlayers, [gameId, players]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#updateGamePlayers, [gameId, players]),
              ),
            ),
          )
          as _i8.Future<_i3.Game>);

  @override
  _i8.Future<_i4.StartGameResult> startGame({
    required String? gameId,
    required List<_i10.PlayerEmbed>? players,
    required String? firstDealerPlayerId,
    required _i5.Round? firstRound,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startGame, [], {
              #gameId: gameId,
              #players: players,
              #firstDealerPlayerId: firstDealerPlayerId,
              #firstRound: firstRound,
            }),
            returnValue: _i8.Future<_i4.StartGameResult>.value(
              _FakeStartGameResult_2(
                this,
                Invocation.method(#startGame, [], {
                  #gameId: gameId,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                  #firstRound: firstRound,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.StartGameResult>.value(
              _FakeStartGameResult_2(
                this,
                Invocation.method(#startGame, [], {
                  #gameId: gameId,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                  #firstRound: firstRound,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.StartGameResult>);

  @override
  _i8.Future<void> revertGameToSetup(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#revertGameToSetup, [gameId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.Round> closeRoundAndUpdateScores({
    required _i5.Round? closedRound,
    required List<_i10.PlayerEmbed>? updatedPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#closeRoundAndUpdateScores, [], {
              #closedRound: closedRound,
              #updatedPlayers: updatedPlayers,
            }),
            returnValue: _i8.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#closeRoundAndUpdateScores, [], {
                  #closedRound: closedRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#closeRoundAndUpdateScores, [], {
                  #closedRound: closedRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.Round>);

  @override
  _i8.Future<_i5.Round> repeatRoundAndRevertScores({
    required _i5.Round? resetRound,
    required List<_i10.PlayerEmbed>? updatedPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#repeatRoundAndRevertScores, [], {
              #resetRound: resetRound,
              #updatedPlayers: updatedPlayers,
            }),
            returnValue: _i8.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#repeatRoundAndRevertScores, [], {
                  #resetRound: resetRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#repeatRoundAndRevertScores, [], {
                  #resetRound: resetRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.Round>);

  @override
  _i8.Future<_i5.Round> advanceToNextRound({
    required _i5.Round? nextRound,
    required int? nextRoundNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#advanceToNextRound, [], {
              #nextRound: nextRound,
              #nextRoundNumber: nextRoundNumber,
            }),
            returnValue: _i8.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#advanceToNextRound, [], {
                  #nextRound: nextRound,
                  #nextRoundNumber: nextRoundNumber,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#advanceToNextRound, [], {
                  #nextRound: nextRound,
                  #nextRoundNumber: nextRoundNumber,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.Round>);

  @override
  _i8.Future<_i3.Game> finishGame({
    required String? gameId,
    required DateTime? finishedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finishGame, [], {
              #gameId: gameId,
              #finishedAt: finishedAt,
            }),
            returnValue: _i8.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#finishGame, [], {
                  #gameId: gameId,
                  #finishedAt: finishedAt,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#finishGame, [], {
                  #gameId: gameId,
                  #finishedAt: finishedAt,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Game>);

  @override
  _i8.Future<void> deleteGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGame, [gameId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> countUnsyncedGames() =>
      (super.noSuchMethod(
            Invocation.method(#countUnsyncedGames, []),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> clearAllLocalData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllLocalData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [FavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRepository extends _i1.Mock
    implements _i11.FavoriteRepository {
  @override
  _i8.Future<List<_i6.FavoritePlayer>> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue: _i8.Future<List<_i6.FavoritePlayer>>.value(
              <_i6.FavoritePlayer>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i6.FavoritePlayer>>.value(
                  <_i6.FavoritePlayer>[],
                ),
          )
          as _i8.Future<List<_i6.FavoritePlayer>>);

  @override
  _i8.Future<_i6.FavoritePlayer> addFavorite({
    required String? displayName,
    String? userId,
    String? photoURL,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [], {
              #displayName: displayName,
              #userId: userId,
              #photoURL: photoURL,
            }),
            returnValue: _i8.Future<_i6.FavoritePlayer>.value(
              _FakeFavoritePlayer_4(
                this,
                Invocation.method(#addFavorite, [], {
                  #displayName: displayName,
                  #userId: userId,
                  #photoURL: photoURL,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.FavoritePlayer>.value(
              _FakeFavoritePlayer_4(
                this,
                Invocation.method(#addFavorite, [], {
                  #displayName: displayName,
                  #userId: userId,
                  #photoURL: photoURL,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.FavoritePlayer>);

  @override
  _i8.Future<void> removeFavorite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavorite, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [LocalUserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalUserService extends _i1.Mock implements _i12.LocalUserService {
  @override
  bool hasLocalId() =>
      (super.noSuchMethod(
            Invocation.method(#hasLocalId, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<String> getOrCreateLocalId() =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateLocalId, []),
            returnValue: _i8.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateLocalId, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateLocalId, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> setLocalName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#setLocalName, [name]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
