// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/auth/presentation/bloc/profile_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:la_pocha/features/auth/domain/entities/player_stats.dart'
    as _i2;
import 'package:la_pocha/features/auth/domain/entities/user_profile.dart'
    as _i3;
import 'package:la_pocha/features/auth/domain/usecases/delete_account_usecase.dart'
    as _i8;
import 'package:la_pocha/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i4;
import 'package:la_pocha/features/auth/domain/usecases/get_player_stats_usecase.dart'
    as _i6;
import 'package:la_pocha/features/auth/domain/usecases/update_display_name_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlayerStats_0 extends _i1.SmartFake implements _i2.PlayerStats {
  _FakePlayerStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_1 extends _i1.SmartFake implements _i3.UserProfile {
  _FakeUserProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i4.GetCurrentUserUseCase {
  @override
  _i5.Future<_i3.UserProfile?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<_i3.UserProfile?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.UserProfile?>.value(),
          )
          as _i5.Future<_i3.UserProfile?>);
}

/// A class which mocks [GetPlayerStatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPlayerStatsUseCase extends _i1.Mock
    implements _i6.GetPlayerStatsUseCase {
  @override
  _i5.Future<_i2.PlayerStats> call({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#userId: userId}),
            returnValue: _i5.Future<_i2.PlayerStats>.value(
              _FakePlayerStats_0(
                this,
                Invocation.method(#call, [], {#userId: userId}),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.PlayerStats>.value(
              _FakePlayerStats_0(
                this,
                Invocation.method(#call, [], {#userId: userId}),
              ),
            ),
          )
          as _i5.Future<_i2.PlayerStats>);
}

/// A class which mocks [UpdateDisplayNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateDisplayNameUseCase extends _i1.Mock
    implements _i7.UpdateDisplayNameUseCase {
  @override
  _i5.Future<_i3.UserProfile> call(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#call, [displayName]),
            returnValue: _i5.Future<_i3.UserProfile>.value(
              _FakeUserProfile_1(this, Invocation.method(#call, [displayName])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.UserProfile>.value(
              _FakeUserProfile_1(this, Invocation.method(#call, [displayName])),
            ),
          )
          as _i5.Future<_i3.UserProfile>);
}

/// A class which mocks [DeleteAccountUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAccountUseCase extends _i1.Mock
    implements _i8.DeleteAccountUseCase {
  @override
  _i5.Future<void> call({String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#password: password}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
