// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/favorites/presentation/bloc/favorites_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:la_pocha/features/favorites/domain/entities/favorite_player.dart'
    as _i2;
import 'package:la_pocha/features/favorites/domain/usecases/add_favorite_usecase.dart'
    as _i5;
import 'package:la_pocha/features/favorites/domain/usecases/get_favorites_usecase.dart'
    as _i3;
import 'package:la_pocha/features/favorites/domain/usecases/remove_favorite_usecase.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFavoritePlayer_0 extends _i1.SmartFake
    implements _i2.FavoritePlayer {
  _FakeFavoritePlayer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetFavoritesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavoritesUseCase extends _i1.Mock
    implements _i3.GetFavoritesUseCase {
  @override
  _i4.Future<List<_i2.FavoritePlayer>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i2.FavoritePlayer>>.value(
              <_i2.FavoritePlayer>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i2.FavoritePlayer>>.value(
                  <_i2.FavoritePlayer>[],
                ),
          )
          as _i4.Future<List<_i2.FavoritePlayer>>);
}

/// A class which mocks [AddFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddFavoriteUseCase extends _i1.Mock
    implements _i5.AddFavoriteUseCase {
  @override
  _i4.Future<_i2.FavoritePlayer> call({
    required String? displayName,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #displayName: displayName,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.FavoritePlayer>.value(
              _FakeFavoritePlayer_0(
                this,
                Invocation.method(#call, [], {
                  #displayName: displayName,
                  #userId: userId,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.FavoritePlayer>.value(
              _FakeFavoritePlayer_0(
                this,
                Invocation.method(#call, [], {
                  #displayName: displayName,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.FavoritePlayer>);
}

/// A class which mocks [RemoveFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveFavoriteUseCase extends _i1.Mock
    implements _i6.RemoveFavoriteUseCase {
  @override
  _i4.Future<void> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
