// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/round/presentation/bloc/bidding_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:la_pocha/features/game_setup/domain/entities/round.dart' as _i4;
import 'package:la_pocha/features/round/domain/entities/bidding_context.dart'
    as _i2;
import 'package:la_pocha/features/round/domain/entities/submit_bid_result.dart'
    as _i3;
import 'package:la_pocha/features/round/domain/usecases/close_bidding_usecase.dart'
    as _i9;
import 'package:la_pocha/features/round/domain/usecases/load_bidding_context_usecase.dart'
    as _i5;
import 'package:la_pocha/features/round/domain/usecases/submit_bid_usecase.dart'
    as _i7;
import 'package:la_pocha/features/round/domain/usecases/update_bid_usecase.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBiddingContext_0 extends _i1.SmartFake
    implements _i2.BiddingContext {
  _FakeBiddingContext_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubmitBidResult_1 extends _i1.SmartFake
    implements _i3.SubmitBidResult {
  _FakeSubmitBidResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRound_2 extends _i1.SmartFake implements _i4.Round {
  _FakeRound_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoadBiddingContextUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadBiddingContextUseCase extends _i1.Mock
    implements _i5.LoadBiddingContextUseCase {
  @override
  _i6.Future<_i2.BiddingContext> call({
    required String? gameId,
    required int? roundNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #gameId: gameId,
              #roundNumber: roundNumber,
            }),
            returnValue: _i6.Future<_i2.BiddingContext>.value(
              _FakeBiddingContext_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #roundNumber: roundNumber,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.BiddingContext>.value(
              _FakeBiddingContext_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #roundNumber: roundNumber,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.BiddingContext>);
}

/// A class which mocks [SubmitBidUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmitBidUseCase extends _i1.Mock implements _i7.SubmitBidUseCase {
  @override
  _i6.Future<_i3.SubmitBidResult> call({
    required _i4.Round? round,
    required List<String>? biddingOrder,
    required String? currentPlayerId,
    required int? bid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #round: round,
              #biddingOrder: biddingOrder,
              #currentPlayerId: currentPlayerId,
              #bid: bid,
            }),
            returnValue: _i6.Future<_i3.SubmitBidResult>.value(
              _FakeSubmitBidResult_1(
                this,
                Invocation.method(#call, [], {
                  #round: round,
                  #biddingOrder: biddingOrder,
                  #currentPlayerId: currentPlayerId,
                  #bid: bid,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.SubmitBidResult>.value(
              _FakeSubmitBidResult_1(
                this,
                Invocation.method(#call, [], {
                  #round: round,
                  #biddingOrder: biddingOrder,
                  #currentPlayerId: currentPlayerId,
                  #bid: bid,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.SubmitBidResult>);
}

/// A class which mocks [UpdateBidUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateBidUseCase extends _i1.Mock implements _i8.UpdateBidUseCase {
  @override
  _i6.Future<_i4.Round> call({
    required _i4.Round? round,
    required String? playerId,
    required int? newBid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #round: round,
              #playerId: playerId,
              #newBid: newBid,
            }),
            returnValue: _i6.Future<_i4.Round>.value(
              _FakeRound_2(
                this,
                Invocation.method(#call, [], {
                  #round: round,
                  #playerId: playerId,
                  #newBid: newBid,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Round>.value(
              _FakeRound_2(
                this,
                Invocation.method(#call, [], {
                  #round: round,
                  #playerId: playerId,
                  #newBid: newBid,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Round>);
}

/// A class which mocks [CloseBiddingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloseBiddingUseCase extends _i1.Mock
    implements _i9.CloseBiddingUseCase {
  @override
  _i6.Future<_i4.Round> call({
    required _i4.Round? round,
    required List<String>? playerIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #round: round,
              #playerIds: playerIds,
            }),
            returnValue: _i6.Future<_i4.Round>.value(
              _FakeRound_2(
                this,
                Invocation.method(#call, [], {
                  #round: round,
                  #playerIds: playerIds,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.Round>.value(
              _FakeRound_2(
                this,
                Invocation.method(#call, [], {
                  #round: round,
                  #playerIds: playerIds,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Round>);
}
