// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/round/presentation/bloc/play_state_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:la_pocha/features/game_setup/domain/entities/round.dart' as _i3;
import 'package:la_pocha/features/round/domain/entities/round_play_state.dart'
    as _i2;
import 'package:la_pocha/features/round/domain/usecases/correct_bids_usecase.dart'
    as _i6;
import 'package:la_pocha/features/round/domain/usecases/get_round_play_state_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRoundPlayState_0 extends _i1.SmartFake
    implements _i2.RoundPlayState {
  _FakeRoundPlayState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRound_1 extends _i1.SmartFake implements _i3.Round {
  _FakeRound_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetRoundPlayStateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRoundPlayStateUseCase extends _i1.Mock
    implements _i4.GetRoundPlayStateUseCase {
  @override
  _i5.Future<_i2.RoundPlayState> call({
    required String? gameId,
    required int? roundNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #gameId: gameId,
              #roundNumber: roundNumber,
            }),
            returnValue: _i5.Future<_i2.RoundPlayState>.value(
              _FakeRoundPlayState_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #roundNumber: roundNumber,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.RoundPlayState>.value(
              _FakeRoundPlayState_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #roundNumber: roundNumber,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.RoundPlayState>);
}

/// A class which mocks [CorrectBidsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCorrectBidsUseCase extends _i1.Mock
    implements _i6.CorrectBidsUseCase {
  @override
  _i5.Future<_i3.Round> call({
    required _i3.Round? round,
    required Map<String, int>? updatedBids,
    required List<String>? playerIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #round: round,
              #updatedBids: updatedBids,
              #playerIds: playerIds,
            }),
            returnValue: _i5.Future<_i3.Round>.value(
              _FakeRound_1(
                this,
                Invocation.method(#call, [], {
                  #round: round,
                  #updatedBids: updatedBids,
                  #playerIds: playerIds,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Round>.value(
              _FakeRound_1(
                this,
                Invocation.method(#call, [], {
                  #round: round,
                  #updatedBids: updatedBids,
                  #playerIds: playerIds,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Round>);
}
