// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/history/domain/usecases/get_recent_games_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:la_pocha/features/history/domain/entities/game_detail.dart'
    as _i3;
import 'package:la_pocha/features/history/domain/entities/game_history_item.dart'
    as _i6;
import 'package:la_pocha/features/history/domain/entities/game_history_load_result.dart'
    as _i2;
import 'package:la_pocha/features/history/domain/entities/game_history_source.dart'
    as _i7;
import 'package:la_pocha/features/history/domain/repositories/history_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGameHistoryLoadResult_0 extends _i1.SmartFake
    implements _i2.GameHistoryLoadResult {
  _FakeGameHistoryLoadResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameDetail_1 extends _i1.SmartFake implements _i3.GameDetail {
  _FakeGameDetail_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i4.HistoryRepository {
  @override
  _i5.Future<_i2.GameHistoryLoadResult> getGameHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getGameHistory, []),
            returnValue: _i5.Future<_i2.GameHistoryLoadResult>.value(
              _FakeGameHistoryLoadResult_0(
                this,
                Invocation.method(#getGameHistory, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.GameHistoryLoadResult>.value(
                  _FakeGameHistoryLoadResult_0(
                    this,
                    Invocation.method(#getGameHistory, []),
                  ),
                ),
          )
          as _i5.Future<_i2.GameHistoryLoadResult>);

  @override
  _i5.Stream<_i2.GameHistoryLoadResult> watchGameHistory() =>
      (super.noSuchMethod(
            Invocation.method(#watchGameHistory, []),
            returnValue: _i5.Stream<_i2.GameHistoryLoadResult>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i2.GameHistoryLoadResult>.empty(),
          )
          as _i5.Stream<_i2.GameHistoryLoadResult>);

  @override
  _i5.Future<List<_i6.GameHistoryItem>> getRecentFinishedGames({
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentFinishedGames, [], {#limit: limit}),
            returnValue: _i5.Future<List<_i6.GameHistoryItem>>.value(
              <_i6.GameHistoryItem>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i6.GameHistoryItem>>.value(
                  <_i6.GameHistoryItem>[],
                ),
          )
          as _i5.Future<List<_i6.GameHistoryItem>>);

  @override
  _i5.Stream<List<_i6.GameHistoryItem>> watchRecentFinishedGames({
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchRecentFinishedGames, [], {#limit: limit}),
            returnValue: _i5.Stream<List<_i6.GameHistoryItem>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<List<_i6.GameHistoryItem>>.empty(),
          )
          as _i5.Stream<List<_i6.GameHistoryItem>>);

  @override
  _i5.Future<_i3.GameDetail> getGameDetail({
    required String? gameId,
    required _i7.GameHistorySource? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGameDetail, [], {
              #gameId: gameId,
              #source: source,
            }),
            returnValue: _i5.Future<_i3.GameDetail>.value(
              _FakeGameDetail_1(
                this,
                Invocation.method(#getGameDetail, [], {
                  #gameId: gameId,
                  #source: source,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.GameDetail>.value(
              _FakeGameDetail_1(
                this,
                Invocation.method(#getGameDetail, [], {
                  #gameId: gameId,
                  #source: source,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.GameDetail>);

  @override
  _i5.Future<void> deleteLocalGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalGame, [gameId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> hideCloudGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#hideCloudGame, [gameId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearHiddenGames() =>
      (super.noSuchMethod(
            Invocation.method(#clearHiddenGames, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
