// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/history/domain/usecases/hide_cloud_game_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:la_pocha/features/game_setup/domain/entities/game.dart' as _i4;
import 'package:la_pocha/features/game_setup/domain/entities/player_embed.dart'
    as _i12;
import 'package:la_pocha/features/game_setup/domain/entities/round.dart' as _i6;
import 'package:la_pocha/features/game_setup/domain/entities/start_game_result.dart'
    as _i5;
import 'package:la_pocha/features/game_setup/domain/repositories/game_repository.dart'
    as _i11;
import 'package:la_pocha/features/history/data/datasources/history_firestore_datasource.dart'
    as _i13;
import 'package:la_pocha/features/history/domain/entities/game_detail.dart'
    as _i3;
import 'package:la_pocha/features/history/domain/entities/game_history_item.dart'
    as _i9;
import 'package:la_pocha/features/history/domain/entities/game_history_load_result.dart'
    as _i2;
import 'package:la_pocha/features/history/domain/entities/game_history_source.dart'
    as _i10;
import 'package:la_pocha/features/history/domain/repositories/history_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGameHistoryLoadResult_0 extends _i1.SmartFake
    implements _i2.GameHistoryLoadResult {
  _FakeGameHistoryLoadResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameDetail_1 extends _i1.SmartFake implements _i3.GameDetail {
  _FakeGameDetail_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGame_2 extends _i1.SmartFake implements _i4.Game {
  _FakeGame_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStartGameResult_3 extends _i1.SmartFake
    implements _i5.StartGameResult {
  _FakeStartGameResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRound_4 extends _i1.SmartFake implements _i6.Round {
  _FakeRound_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i7.HistoryRepository {
  @override
  _i8.Future<_i2.GameHistoryLoadResult> getGameHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getGameHistory, []),
            returnValue: _i8.Future<_i2.GameHistoryLoadResult>.value(
              _FakeGameHistoryLoadResult_0(
                this,
                Invocation.method(#getGameHistory, []),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i2.GameHistoryLoadResult>.value(
                  _FakeGameHistoryLoadResult_0(
                    this,
                    Invocation.method(#getGameHistory, []),
                  ),
                ),
          )
          as _i8.Future<_i2.GameHistoryLoadResult>);

  @override
  _i8.Stream<_i2.GameHistoryLoadResult> watchGameHistory() =>
      (super.noSuchMethod(
            Invocation.method(#watchGameHistory, []),
            returnValue: _i8.Stream<_i2.GameHistoryLoadResult>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.GameHistoryLoadResult>.empty(),
          )
          as _i8.Stream<_i2.GameHistoryLoadResult>);

  @override
  _i8.Future<List<_i9.GameHistoryItem>> getRecentFinishedGames({
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentFinishedGames, [], {#limit: limit}),
            returnValue: _i8.Future<List<_i9.GameHistoryItem>>.value(
              <_i9.GameHistoryItem>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i9.GameHistoryItem>>.value(
                  <_i9.GameHistoryItem>[],
                ),
          )
          as _i8.Future<List<_i9.GameHistoryItem>>);

  @override
  _i8.Stream<List<_i9.GameHistoryItem>> watchRecentFinishedGames({
    int? limit = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchRecentFinishedGames, [], {#limit: limit}),
            returnValue: _i8.Stream<List<_i9.GameHistoryItem>>.empty(),
            returnValueForMissingStub:
                _i8.Stream<List<_i9.GameHistoryItem>>.empty(),
          )
          as _i8.Stream<List<_i9.GameHistoryItem>>);

  @override
  _i8.Future<_i3.GameDetail> getGameDetail({
    required String? gameId,
    required _i10.GameHistorySource? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGameDetail, [], {
              #gameId: gameId,
              #source: source,
            }),
            returnValue: _i8.Future<_i3.GameDetail>.value(
              _FakeGameDetail_1(
                this,
                Invocation.method(#getGameDetail, [], {
                  #gameId: gameId,
                  #source: source,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.GameDetail>.value(
              _FakeGameDetail_1(
                this,
                Invocation.method(#getGameDetail, [], {
                  #gameId: gameId,
                  #source: source,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.GameDetail>);

  @override
  _i8.Future<void> deleteLocalGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLocalGame, [gameId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> hideCloudGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#hideCloudGame, [gameId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearHiddenGames() =>
      (super.noSuchMethod(
            Invocation.method(#clearHiddenGames, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i11.GameRepository {
  @override
  _i8.Future<_i4.Game> saveDraft(_i4.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [game]),
            returnValue: _i8.Future<_i4.Game>.value(
              _FakeGame_2(this, Invocation.method(#saveDraft, [game])),
            ),
            returnValueForMissingStub: _i8.Future<_i4.Game>.value(
              _FakeGame_2(this, Invocation.method(#saveDraft, [game])),
            ),
          )
          as _i8.Future<_i4.Game>);

  @override
  _i8.Future<_i4.Game?> getGameById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGameById, [id]),
            returnValue: _i8.Future<_i4.Game?>.value(),
            returnValueForMissingStub: _i8.Future<_i4.Game?>.value(),
          )
          as _i8.Future<_i4.Game?>);

  @override
  _i8.Future<_i4.Game?> getInProgressGame() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressGame, []),
            returnValue: _i8.Future<_i4.Game?>.value(),
            returnValueForMissingStub: _i8.Future<_i4.Game?>.value(),
          )
          as _i8.Future<_i4.Game?>);

  @override
  _i8.Future<_i4.Game> updateGamePlayers(
    String? gameId,
    List<_i12.PlayerEmbed>? players,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGamePlayers, [gameId, players]),
            returnValue: _i8.Future<_i4.Game>.value(
              _FakeGame_2(
                this,
                Invocation.method(#updateGamePlayers, [gameId, players]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.Game>.value(
              _FakeGame_2(
                this,
                Invocation.method(#updateGamePlayers, [gameId, players]),
              ),
            ),
          )
          as _i8.Future<_i4.Game>);

  @override
  _i8.Future<_i5.StartGameResult> startGame({
    required String? gameId,
    required List<_i12.PlayerEmbed>? players,
    required String? firstDealerPlayerId,
    required _i6.Round? firstRound,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startGame, [], {
              #gameId: gameId,
              #players: players,
              #firstDealerPlayerId: firstDealerPlayerId,
              #firstRound: firstRound,
            }),
            returnValue: _i8.Future<_i5.StartGameResult>.value(
              _FakeStartGameResult_3(
                this,
                Invocation.method(#startGame, [], {
                  #gameId: gameId,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                  #firstRound: firstRound,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.StartGameResult>.value(
              _FakeStartGameResult_3(
                this,
                Invocation.method(#startGame, [], {
                  #gameId: gameId,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                  #firstRound: firstRound,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.StartGameResult>);

  @override
  _i8.Future<void> revertGameToSetup(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#revertGameToSetup, [gameId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.Round> closeRoundAndUpdateScores({
    required _i6.Round? closedRound,
    required List<_i12.PlayerEmbed>? updatedPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#closeRoundAndUpdateScores, [], {
              #closedRound: closedRound,
              #updatedPlayers: updatedPlayers,
            }),
            returnValue: _i8.Future<_i6.Round>.value(
              _FakeRound_4(
                this,
                Invocation.method(#closeRoundAndUpdateScores, [], {
                  #closedRound: closedRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.Round>.value(
              _FakeRound_4(
                this,
                Invocation.method(#closeRoundAndUpdateScores, [], {
                  #closedRound: closedRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.Round>);

  @override
  _i8.Future<_i6.Round> repeatRoundAndRevertScores({
    required _i6.Round? resetRound,
    required List<_i12.PlayerEmbed>? updatedPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#repeatRoundAndRevertScores, [], {
              #resetRound: resetRound,
              #updatedPlayers: updatedPlayers,
            }),
            returnValue: _i8.Future<_i6.Round>.value(
              _FakeRound_4(
                this,
                Invocation.method(#repeatRoundAndRevertScores, [], {
                  #resetRound: resetRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.Round>.value(
              _FakeRound_4(
                this,
                Invocation.method(#repeatRoundAndRevertScores, [], {
                  #resetRound: resetRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.Round>);

  @override
  _i8.Future<_i6.Round> advanceToNextRound({
    required _i6.Round? nextRound,
    required int? nextRoundNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#advanceToNextRound, [], {
              #nextRound: nextRound,
              #nextRoundNumber: nextRoundNumber,
            }),
            returnValue: _i8.Future<_i6.Round>.value(
              _FakeRound_4(
                this,
                Invocation.method(#advanceToNextRound, [], {
                  #nextRound: nextRound,
                  #nextRoundNumber: nextRoundNumber,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.Round>.value(
              _FakeRound_4(
                this,
                Invocation.method(#advanceToNextRound, [], {
                  #nextRound: nextRound,
                  #nextRoundNumber: nextRoundNumber,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.Round>);

  @override
  _i8.Future<_i4.Game> finishGame({
    required String? gameId,
    required DateTime? finishedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finishGame, [], {
              #gameId: gameId,
              #finishedAt: finishedAt,
            }),
            returnValue: _i8.Future<_i4.Game>.value(
              _FakeGame_2(
                this,
                Invocation.method(#finishGame, [], {
                  #gameId: gameId,
                  #finishedAt: finishedAt,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.Game>.value(
              _FakeGame_2(
                this,
                Invocation.method(#finishGame, [], {
                  #gameId: gameId,
                  #finishedAt: finishedAt,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.Game>);

  @override
  _i8.Future<void> deleteGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGame, [gameId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [HistoryFirestoreDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryFirestoreDatasource extends _i1.Mock
    implements _i13.HistoryFirestoreDatasource {
  @override
  _i8.Future<List<_i9.GameHistoryItem>> getFinishedCloudGames() =>
      (super.noSuchMethod(
            Invocation.method(#getFinishedCloudGames, []),
            returnValue: _i8.Future<List<_i9.GameHistoryItem>>.value(
              <_i9.GameHistoryItem>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i9.GameHistoryItem>>.value(
                  <_i9.GameHistoryItem>[],
                ),
          )
          as _i8.Future<List<_i9.GameHistoryItem>>);

  @override
  _i8.Future<({_i4.Game game, List<_i6.Round> rounds})> loadFinishedGameDetail(
    String? gameId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadFinishedGameDetail, [gameId]),
            returnValue:
                _i8.Future<({_i4.Game game, List<_i6.Round> rounds})>.value((
                  game: _FakeGame_2(
                    this,
                    Invocation.method(#loadFinishedGameDetail, [gameId]),
                  ),
                  rounds: <_i6.Round>[],
                )),
            returnValueForMissingStub:
                _i8.Future<({_i4.Game game, List<_i6.Round> rounds})>.value((
                  game: _FakeGame_2(
                    this,
                    Invocation.method(#loadFinishedGameDetail, [gameId]),
                  ),
                  rounds: <_i6.Round>[],
                )),
          )
          as _i8.Future<({_i4.Game game, List<_i6.Round> rounds})>);
}
