// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/history/domain/usecases/repeat_game_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:la_pocha/features/game_setup/domain/entities/game.dart' as _i3;
import 'package:la_pocha/features/game_setup/domain/entities/player_embed.dart'
    as _i10;
import 'package:la_pocha/features/game_setup/domain/entities/round.dart' as _i5;
import 'package:la_pocha/features/game_setup/domain/entities/start_game_result.dart'
    as _i4;
import 'package:la_pocha/features/game_setup/domain/repositories/game_repository.dart'
    as _i9;
import 'package:la_pocha/features/game_setup/domain/services/game_cloner_service.dart'
    as _i11;
import 'package:la_pocha/features/history/domain/entities/game_detail.dart'
    as _i2;
import 'package:la_pocha/features/history/domain/entities/game_history_source.dart'
    as _i8;
import 'package:la_pocha/features/history/domain/usecases/get_game_detail_usecase.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGameDetail_0 extends _i1.SmartFake implements _i2.GameDetail {
  _FakeGameDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGame_1 extends _i1.SmartFake implements _i3.Game {
  _FakeGame_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStartGameResult_2 extends _i1.SmartFake
    implements _i4.StartGameResult {
  _FakeStartGameResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRound_3 extends _i1.SmartFake implements _i5.Round {
  _FakeRound_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetGameDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGameDetailUseCase extends _i1.Mock
    implements _i6.GetGameDetailUseCase {
  @override
  _i7.Future<_i2.GameDetail> call({
    required String? gameId,
    required _i8.GameHistorySource? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#gameId: gameId, #source: source}),
            returnValue: _i7.Future<_i2.GameDetail>.value(
              _FakeGameDetail_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #source: source,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.GameDetail>.value(
              _FakeGameDetail_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #source: source,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.GameDetail>);
}

/// A class which mocks [GameRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRepository extends _i1.Mock implements _i9.GameRepository {
  @override
  _i7.Future<_i3.Game> saveDraft(_i3.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [game]),
            returnValue: _i7.Future<_i3.Game>.value(
              _FakeGame_1(this, Invocation.method(#saveDraft, [game])),
            ),
            returnValueForMissingStub: _i7.Future<_i3.Game>.value(
              _FakeGame_1(this, Invocation.method(#saveDraft, [game])),
            ),
          )
          as _i7.Future<_i3.Game>);

  @override
  _i7.Future<_i3.Game?> getGameById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGameById, [id]),
            returnValue: _i7.Future<_i3.Game?>.value(),
            returnValueForMissingStub: _i7.Future<_i3.Game?>.value(),
          )
          as _i7.Future<_i3.Game?>);

  @override
  _i7.Future<_i3.Game?> getInProgressGame() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressGame, []),
            returnValue: _i7.Future<_i3.Game?>.value(),
            returnValueForMissingStub: _i7.Future<_i3.Game?>.value(),
          )
          as _i7.Future<_i3.Game?>);

  @override
  _i7.Future<_i3.Game> updateGamePlayers(
    String? gameId,
    List<_i10.PlayerEmbed>? players,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGamePlayers, [gameId, players]),
            returnValue: _i7.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#updateGamePlayers, [gameId, players]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#updateGamePlayers, [gameId, players]),
              ),
            ),
          )
          as _i7.Future<_i3.Game>);

  @override
  _i7.Future<_i4.StartGameResult> startGame({
    required String? gameId,
    required List<_i10.PlayerEmbed>? players,
    required String? firstDealerPlayerId,
    required _i5.Round? firstRound,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startGame, [], {
              #gameId: gameId,
              #players: players,
              #firstDealerPlayerId: firstDealerPlayerId,
              #firstRound: firstRound,
            }),
            returnValue: _i7.Future<_i4.StartGameResult>.value(
              _FakeStartGameResult_2(
                this,
                Invocation.method(#startGame, [], {
                  #gameId: gameId,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                  #firstRound: firstRound,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.StartGameResult>.value(
              _FakeStartGameResult_2(
                this,
                Invocation.method(#startGame, [], {
                  #gameId: gameId,
                  #players: players,
                  #firstDealerPlayerId: firstDealerPlayerId,
                  #firstRound: firstRound,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.StartGameResult>);

  @override
  _i7.Future<void> revertGameToSetup(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#revertGameToSetup, [gameId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.Round> closeRoundAndUpdateScores({
    required _i5.Round? closedRound,
    required List<_i10.PlayerEmbed>? updatedPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#closeRoundAndUpdateScores, [], {
              #closedRound: closedRound,
              #updatedPlayers: updatedPlayers,
            }),
            returnValue: _i7.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#closeRoundAndUpdateScores, [], {
                  #closedRound: closedRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#closeRoundAndUpdateScores, [], {
                  #closedRound: closedRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.Round>);

  @override
  _i7.Future<_i5.Round> repeatRoundAndRevertScores({
    required _i5.Round? resetRound,
    required List<_i10.PlayerEmbed>? updatedPlayers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#repeatRoundAndRevertScores, [], {
              #resetRound: resetRound,
              #updatedPlayers: updatedPlayers,
            }),
            returnValue: _i7.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#repeatRoundAndRevertScores, [], {
                  #resetRound: resetRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#repeatRoundAndRevertScores, [], {
                  #resetRound: resetRound,
                  #updatedPlayers: updatedPlayers,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.Round>);

  @override
  _i7.Future<_i5.Round> advanceToNextRound({
    required _i5.Round? nextRound,
    required int? nextRoundNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#advanceToNextRound, [], {
              #nextRound: nextRound,
              #nextRoundNumber: nextRoundNumber,
            }),
            returnValue: _i7.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#advanceToNextRound, [], {
                  #nextRound: nextRound,
                  #nextRoundNumber: nextRoundNumber,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.Round>.value(
              _FakeRound_3(
                this,
                Invocation.method(#advanceToNextRound, [], {
                  #nextRound: nextRound,
                  #nextRoundNumber: nextRoundNumber,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.Round>);

  @override
  _i7.Future<_i3.Game> finishGame({
    required String? gameId,
    required DateTime? finishedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finishGame, [], {
              #gameId: gameId,
              #finishedAt: finishedAt,
            }),
            returnValue: _i7.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#finishGame, [], {
                  #gameId: gameId,
                  #finishedAt: finishedAt,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.Game>.value(
              _FakeGame_1(
                this,
                Invocation.method(#finishGame, [], {
                  #gameId: gameId,
                  #finishedAt: finishedAt,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.Game>);

  @override
  _i7.Future<void> deleteGame(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGame, [gameId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [GameClonerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameClonerService extends _i1.Mock implements _i11.GameClonerService {
  @override
  _i3.Game cloneForRepeat({
    required _i3.Game? source,
    required String? newGameId,
    required DateTime? now,
    required String Function()? generatePlayerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cloneForRepeat, [], {
              #source: source,
              #newGameId: newGameId,
              #now: now,
              #generatePlayerId: generatePlayerId,
            }),
            returnValue: _FakeGame_1(
              this,
              Invocation.method(#cloneForRepeat, [], {
                #source: source,
                #newGameId: newGameId,
                #now: now,
                #generatePlayerId: generatePlayerId,
              }),
            ),
            returnValueForMissingStub: _FakeGame_1(
              this,
              Invocation.method(#cloneForRepeat, [], {
                #source: source,
                #newGameId: newGameId,
                #now: now,
                #generatePlayerId: generatePlayerId,
              }),
            ),
          )
          as _i3.Game);
}
