// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/history/presentation/bloc/game_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:la_pocha/features/history/domain/entities/game_detail.dart'
    as _i2;
import 'package:la_pocha/features/history/domain/entities/game_history_source.dart'
    as _i5;
import 'package:la_pocha/features/history/domain/usecases/get_game_detail_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGameDetail_0 extends _i1.SmartFake implements _i2.GameDetail {
  _FakeGameDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetGameDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGameDetailUseCase extends _i1.Mock
    implements _i3.GetGameDetailUseCase {
  @override
  _i4.Future<_i2.GameDetail> call({
    required String? gameId,
    required _i5.GameHistorySource? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#gameId: gameId, #source: source}),
            returnValue: _i4.Future<_i2.GameDetail>.value(
              _FakeGameDetail_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #source: source,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.GameDetail>.value(
              _FakeGameDetail_0(
                this,
                Invocation.method(#call, [], {
                  #gameId: gameId,
                  #source: source,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.GameDetail>);
}
