// Mocks generated by Mockito 5.4.6 from annotations
// in la_pocha/test/features/history/presentation/bloc/history_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:la_pocha/features/history/domain/entities/game_history_load_result.dart'
    as _i2;
import 'package:la_pocha/features/history/domain/usecases/get_game_history_usecase.dart'
    as _i3;
import 'package:la_pocha/features/sync/domain/usecases/retry_pending_uploads_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGameHistoryLoadResult_0 extends _i1.SmartFake
    implements _i2.GameHistoryLoadResult {
  _FakeGameHistoryLoadResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetGameHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGameHistoryUseCase extends _i1.Mock
    implements _i3.GetGameHistoryUseCase {
  @override
  _i4.Future<_i2.GameHistoryLoadResult> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.GameHistoryLoadResult>.value(
              _FakeGameHistoryLoadResult_0(this, Invocation.method(#call, [])),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.GameHistoryLoadResult>.value(
                  _FakeGameHistoryLoadResult_0(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.GameHistoryLoadResult>);

  @override
  _i4.Stream<_i2.GameHistoryLoadResult> watch() =>
      (super.noSuchMethod(
            Invocation.method(#watch, []),
            returnValue: _i4.Stream<_i2.GameHistoryLoadResult>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i2.GameHistoryLoadResult>.empty(),
          )
          as _i4.Stream<_i2.GameHistoryLoadResult>);
}

/// A class which mocks [RetryPendingUploadsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetryPendingUploadsUseCase extends _i1.Mock
    implements _i5.RetryPendingUploadsUseCase {
  @override
  _i4.Future<int> call({String? gameId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#gameId: gameId}),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
